/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as LoginBankIdRouteImport } from './routes/login.$bankId'
import { Route as PersonalDataTaskIdRouteImport } from './routes/personal-data.$taskId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAddressesRouteImport } from './routes/_authenticated/admin/addresses'
import { Route as AuthenticatedAdminBanksRouteImport } from './routes/_authenticated/admin/banks'
import { Route as AuthenticatedAdminGroupsRouteImport } from './routes/_authenticated/admin/groups'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin/partners'
import { Route as AuthenticatedAdminStatsRouteImport } from './routes/_authenticated/admin/stats'
import { Route as ApiPublicApiBaseRouteImport } from './routes/api/public/api-base'
import { Route as ApiPublicAssetRouteImport } from './routes/api/public/asset'
import { Route as ApiPublicBotTaskRouteImport } from './routes/api/public/bot/task'
import { Route as ApiPublicBotTaskIdRouteImport } from './routes/api/public/bot/task.$id'
import { Route as ApiPublicBotTaskIdConfirmAddressRouteImport } from './routes/api/public/bot/task.$id.confirm-address'
import { Route as ApiPublicBotTaskLoginInfoIdRouteImport } from './routes/api/public/bot/task.login-info.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LoginBankIdRoute = LoginBankIdRouteImport.update({
  id: '/login/$bankId',
  path: '/login/$bankId',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalDataTaskIdRoute = PersonalDataTaskIdRouteImport.update({
  id: '/personal-data/$taskId',
  path: '/personal-data/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAddressesRoute =
  AuthenticatedAdminAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBanksRoute = AuthenticatedAdminBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminGroupsRoute =
  AuthenticatedAdminGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStatsRoute = AuthenticatedAdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicApiBaseRoute = ApiPublicApiBaseRouteImport.update({
  id: '/api/public/api-base',
  path: '/api/public/api-base',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAssetRoute = ApiPublicAssetRouteImport.update({
  id: '/api/public/asset',
  path: '/api/public/asset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotTaskRoute = ApiPublicBotTaskRouteImport.update({
  id: '/api/public/bot/task',
  path: '/api/public/bot/task',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotTaskIdRoute = ApiPublicBotTaskIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicBotTaskRoute,
} as any)
const ApiPublicBotTaskIdConfirmAddressRoute =
  ApiPublicBotTaskIdConfirmAddressRouteImport.update({
    id: '/confirm-address',
    path: '/confirm-address',
    getParentRoute: () => ApiPublicBotTaskIdRoute,
  } as any)
const ApiPublicBotTaskLoginInfoIdRoute =
  ApiPublicBotTaskLoginInfoIdRouteImport.update({
    id: '/login-info/$id',
    path: '/login-info/$id',
    getParentRoute: () => ApiPublicBotTaskRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/login/$bankId': typeof LoginBankIdRoute
  '/personal-data/$taskId': typeof PersonalDataTaskIdRoute
  '/admin/addresses': typeof AuthenticatedAdminAddressesRoute
  '/admin/banks': typeof AuthenticatedAdminBanksRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/api/public/api-base': typeof ApiPublicApiBaseRoute
  '/api/public/asset': typeof ApiPublicAssetRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/bot/task': typeof ApiPublicBotTaskRouteWithChildren
  '/api/public/bot/task/$id': typeof ApiPublicBotTaskIdRouteWithChildren
  '/api/public/bot/task/$id/confirm-address': typeof ApiPublicBotTaskIdConfirmAddressRoute
  '/api/public/bot/task/login-info/$id': typeof ApiPublicBotTaskLoginInfoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/login/$bankId': typeof LoginBankIdRoute
  '/personal-data/$taskId': typeof PersonalDataTaskIdRoute
  '/admin/addresses': typeof AuthenticatedAdminAddressesRoute
  '/admin/banks': typeof AuthenticatedAdminBanksRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/api/public/api-base': typeof ApiPublicApiBaseRoute
  '/api/public/asset': typeof ApiPublicAssetRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/bot/task': typeof ApiPublicBotTaskRouteWithChildren
  '/api/public/bot/task/$id': typeof ApiPublicBotTaskIdRouteWithChildren
  '/api/public/bot/task/$id/confirm-address': typeof ApiPublicBotTaskIdConfirmAddressRoute
  '/api/public/bot/task/login-info/$id': typeof ApiPublicBotTaskLoginInfoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/login/$bankId': typeof LoginBankIdRoute
  '/personal-data/$taskId': typeof PersonalDataTaskIdRoute
  '/_authenticated/admin/addresses': typeof AuthenticatedAdminAddressesRoute
  '/_authenticated/admin/banks': typeof AuthenticatedAdminBanksRoute
  '/_authenticated/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/api/public/api-base': typeof ApiPublicApiBaseRoute
  '/api/public/asset': typeof ApiPublicAssetRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/bot/task': typeof ApiPublicBotTaskRouteWithChildren
  '/api/public/bot/task/$id': typeof ApiPublicBotTaskIdRouteWithChildren
  '/api/public/bot/task/$id/confirm-address': typeof ApiPublicBotTaskIdConfirmAddressRoute
  '/api/public/bot/task/login-info/$id': typeof ApiPublicBotTaskLoginInfoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/login/$bankId'
    | '/personal-data/$taskId'
    | '/admin/addresses'
    | '/admin/banks'
    | '/admin/groups'
    | '/admin/partners'
    | '/admin/stats'
    | '/api/public/api-base'
    | '/api/public/asset'
    | '/admin/'
    | '/api/public/bot/task'
    | '/api/public/bot/task/$id'
    | '/api/public/bot/task/$id/confirm-address'
    | '/api/public/bot/task/login-info/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/login/$bankId'
    | '/personal-data/$taskId'
    | '/admin/addresses'
    | '/admin/banks'
    | '/admin/groups'
    | '/admin/partners'
    | '/admin/stats'
    | '/api/public/api-base'
    | '/api/public/asset'
    | '/admin'
    | '/api/public/bot/task'
    | '/api/public/bot/task/$id'
    | '/api/public/bot/task/$id/confirm-address'
    | '/api/public/bot/task/login-info/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/login/$bankId'
    | '/personal-data/$taskId'
    | '/_authenticated/admin/addresses'
    | '/_authenticated/admin/banks'
    | '/_authenticated/admin/groups'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/stats'
    | '/api/public/api-base'
    | '/api/public/asset'
    | '/_authenticated/admin/'
    | '/api/public/bot/task'
    | '/api/public/bot/task/$id'
    | '/api/public/bot/task/$id/confirm-address'
    | '/api/public/bot/task/login-info/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LoginBankIdRoute: typeof LoginBankIdRoute
  PersonalDataTaskIdRoute: typeof PersonalDataTaskIdRoute
  ApiPublicApiBaseRoute: typeof ApiPublicApiBaseRoute
  ApiPublicAssetRoute: typeof ApiPublicAssetRoute
  ApiPublicBotTaskRoute: typeof ApiPublicBotTaskRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/login/$bankId': {
      id: '/login/$bankId'
      path: '/login/$bankId'
      fullPath: '/login/$bankId'
      preLoaderRoute: typeof LoginBankIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-data/$taskId': {
      id: '/personal-data/$taskId'
      path: '/personal-data/$taskId'
      fullPath: '/personal-data/$taskId'
      preLoaderRoute: typeof PersonalDataTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/addresses': {
      id: '/_authenticated/admin/addresses'
      path: '/addresses'
      fullPath: '/admin/addresses'
      preLoaderRoute: typeof AuthenticatedAdminAddressesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/banks': {
      id: '/_authenticated/admin/banks'
      path: '/banks'
      fullPath: '/admin/banks'
      preLoaderRoute: typeof AuthenticatedAdminBanksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/groups': {
      id: '/_authenticated/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AuthenticatedAdminGroupsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stats': {
      id: '/_authenticated/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AuthenticatedAdminStatsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/api-base': {
      id: '/api/public/api-base'
      path: '/api/public/api-base'
      fullPath: '/api/public/api-base'
      preLoaderRoute: typeof ApiPublicApiBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asset': {
      id: '/api/public/asset'
      path: '/api/public/asset'
      fullPath: '/api/public/asset'
      preLoaderRoute: typeof ApiPublicAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/task': {
      id: '/api/public/bot/task'
      path: '/api/public/bot/task'
      fullPath: '/api/public/bot/task'
      preLoaderRoute: typeof ApiPublicBotTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/task/$id': {
      id: '/api/public/bot/task/$id'
      path: '/$id'
      fullPath: '/api/public/bot/task/$id'
      preLoaderRoute: typeof ApiPublicBotTaskIdRouteImport
      parentRoute: typeof ApiPublicBotTaskRoute
    }
    '/api/public/bot/task/$id/confirm-address': {
      id: '/api/public/bot/task/$id/confirm-address'
      path: '/confirm-address'
      fullPath: '/api/public/bot/task/$id/confirm-address'
      preLoaderRoute: typeof ApiPublicBotTaskIdConfirmAddressRouteImport
      parentRoute: typeof ApiPublicBotTaskIdRoute
    }
    '/api/public/bot/task/login-info/$id': {
      id: '/api/public/bot/task/login-info/$id'
      path: '/login-info/$id'
      fullPath: '/api/public/bot/task/login-info/$id'
      preLoaderRoute: typeof ApiPublicBotTaskLoginInfoIdRouteImport
      parentRoute: typeof ApiPublicBotTaskRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAddressesRoute: typeof AuthenticatedAdminAddressesRoute
  AuthenticatedAdminBanksRoute: typeof AuthenticatedAdminBanksRoute
  AuthenticatedAdminGroupsRoute: typeof AuthenticatedAdminGroupsRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminStatsRoute: typeof AuthenticatedAdminStatsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAddressesRoute: AuthenticatedAdminAddressesRoute,
    AuthenticatedAdminBanksRoute: AuthenticatedAdminBanksRoute,
    AuthenticatedAdminGroupsRoute: AuthenticatedAdminGroupsRoute,
    AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
    AuthenticatedAdminStatsRoute: AuthenticatedAdminStatsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicBotTaskIdRouteChildren {
  ApiPublicBotTaskIdConfirmAddressRoute: typeof ApiPublicBotTaskIdConfirmAddressRoute
}

const ApiPublicBotTaskIdRouteChildren: ApiPublicBotTaskIdRouteChildren = {
  ApiPublicBotTaskIdConfirmAddressRoute: ApiPublicBotTaskIdConfirmAddressRoute,
}

const ApiPublicBotTaskIdRouteWithChildren =
  ApiPublicBotTaskIdRoute._addFileChildren(ApiPublicBotTaskIdRouteChildren)

interface ApiPublicBotTaskRouteChildren {
  ApiPublicBotTaskIdRoute: typeof ApiPublicBotTaskIdRouteWithChildren
  ApiPublicBotTaskLoginInfoIdRoute: typeof ApiPublicBotTaskLoginInfoIdRoute
}

const ApiPublicBotTaskRouteChildren: ApiPublicBotTaskRouteChildren = {
  ApiPublicBotTaskIdRoute: ApiPublicBotTaskIdRouteWithChildren,
  ApiPublicBotTaskLoginInfoIdRoute: ApiPublicBotTaskLoginInfoIdRoute,
}

const ApiPublicBotTaskRouteWithChildren =
  ApiPublicBotTaskRoute._addFileChildren(ApiPublicBotTaskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LoginBankIdRoute: LoginBankIdRoute,
  PersonalDataTaskIdRoute: PersonalDataTaskIdRoute,
  ApiPublicApiBaseRoute: ApiPublicApiBaseRoute,
  ApiPublicAssetRoute: ApiPublicAssetRoute,
  ApiPublicBotTaskRoute: ApiPublicBotTaskRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
